id: P005518
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8475
  title: 'ལྷ་ལྡན་གཙུག་ལག་ཁང་། '
  author: ''
  volumes:
    ff562249ad3247ce8757295c9bd24ff3:
      image_group_id: I1KG8513
      title: ''
      volume_number: 1
      total_pages: 70
